vmay-site/photo/category/frameworks_drivers/django/urls.py
from django.urls import path

from category.interface_adapters.controllers.views import CategoryListView

app_name = 'category'

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='categories'),
]

vmay-site/photo/photo/urls.py
import os
from distutils.util import strtobool

from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .settings import base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.frameworks_drivers.django.urls', namespace='home')),
    path('', include('portfolio.frameworks_drivers.django.urls.default', namespace='portfolio')),
    path('', include('category.frameworks_drivers.django.urls', namespace='category')),
    path('', include('condition.frameworks_drivers.django.urls', namespace='condition')),
    path('', include('contact.frameworks_drivers.django.urls', namespace='contact')),
]

if strtobool(os.getenv('DEBUG', 'False')):
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

vmay-site/photo/category/interface_adapters/gateways/models.py
from django.db import models

from extensions.interface_adapters.gateways.mixins.models import DeleteOldImageModelMixin


class Category(models.Model, DeleteOldImageModelMixin):
    name = models.CharField(max_length=128, unique=True, help_text='Назва послуги')
    price = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='category-images')
    description = models.TextField(help_text='Що входить до послуги')
    slug = models.SlugField(max_length=128, unique=True, help_text="individual, love-story, family...")

    class Meta:
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'
        ordering = ['id']

    def __str__(self):
        return f'Категорія: {self.name} | Ціна: {self.price}'

vmay-site/photo/extensions/interface_adapters/gateways/mixins/models.py
class DeleteOldImageModelMixin:
    image_field_name = 'image'

    def save(self, *args, **kwargs):
        if self.pk:
            old = type(self).objects.filter(pk=self.pk).only(self.image_field_name).first()
            fn = getattr(old, self.image_field_name, None)
            if fn and fn != getattr(self, self.image_field_name):
                fn.delete(save=False)
        return super().save(*args, **kwargs)

vmay-site/photo/extensions/interface_adapters/presenters/admin/forms.py
from django import forms
from django.db import models


class SimpleUrlFieldAdmin:
    formfield_overrides = {
        models.URLField: {"widget": forms.TextInput()},
    }

vmay-site/photo/category/interface_adapters/controllers/views.py
from django.views.generic import ListView

from extensions.interface_adapters.controllers.decorators.cache import cache_category
from extensions.interface_adapters.controllers.mixins import TitleMixin
from pkg.application.services.crud import GetAllRepositoryService
from pkg.interface_adapters.di.provider import inject


@cache_category
class CategoryListView(TitleMixin, ListView):
    template_name = 'category/categories.html'
    title = 'vmay - Категорії'

    @inject
    def get_queryset(self, service: GetAllRepositoryService = 'category:get_all'):
        return service()

vmay-site/photo/extensions/interface_adapters/controllers/mixins/views.py
class TitleMixin:
    title = None

    def get_context_data(self, **kwargs):
        context = super(TitleMixin, self).get_context_data(**kwargs)
        context['title'] = self.title
        return context

vmay-site/photo/category/interface_adapters/presenters/templates/category/categories.html
{% extends 'base.html' %}
{% load static extension_tags %}


{% block toolbar %}
    <li style="padding-left: 0 !important;"><a href="{% url 'home:home' %}">Домашня</a></li>
    <li><a href="{% url 'portfolio:portfolio' "all" %}">Портфоліо</a></li>
    <li><a href="{% url 'condition:conditions' %}">Умови</a></li>
    <li><a href="{% url 'category:categories' %}" class="active-txt">Тарифи</a></li>
    <li style="padding-right: 0 !important;"><a href="{% url 'contact:contact' %}">Зв'язок</a></li>
{% endblock %}

{% block banner %}
    <div class="page-heading">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 header-text">
                    <h2><em>Тарифи</em> на послуги</h2>
                    <p></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <br>
    <section class="closed-contests" id="categories" style="margin-top: 0;padding-top: 0; padding-bottom: 0;">
        <div class="container">
            <div class="row" style="display: flex; justify-content: center">
                <div class="row g-4">
                    {% for category in object_list %}
                        <div class="col-lg-4">
                            <div class="pricing-item shadow">
                                <img src="{{ category.image }}" class="img-fluid rounded" alt="">
                                <h4 class="custom-title-font">{{ category.name }}</h4>
                                <p class="marked">{{ category.description|to_p }}</p>
                                <span class="price">₴{{ category.price }} грн</span>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12">
                                        <div class="border-button" style="margin-top: 30px; margin-bottom: 30px">
                                            <a class="w-80p"
                                               href="{% url 'portfolio:portfolio' category.slug %}#gallery">Приклади</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <br>
        </div>
    </section>
{% endblock %}